# Generated by Django 4.2.2 on 2023-06-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('warden_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob_no', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('stud_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mob_no', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gatepasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('stud_id', models.CharField(max_length=10)),
                ('date_out', models.DateField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('warden_approve', models.CharField(choices=[('1', 'accepted'), ('0', 'rejected')], max_length=3)),
                ('date_in', models.DateField(null=True)),
                ('time_in', models.TimeField(null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.student')),
            ],
        ),
    ]
