# Generated by Django 4.2.2 on 2023-08-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
