# Generated by Django 4.2.2 on 2023-08-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0003_mess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('stud_id', models.CharField(max_length=10)),
                ('date_from', models.DateField(null=True)),
                ('date_to', models.DateField(null=True)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=10)),
                ('warden_approve', models.CharField(choices=[('1', 'accepted'), ('0', 'rejected')], max_length=3)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app6.student')),
            ],
        ),
    ]
