# Generated by Django 4.2.1 on 2023-08-14 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0004_messcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=10)),
                ('room_no', models.CharField(max_length=10)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
