# Generated by Django 4.2.1 on 2023-08-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6', '0005_grievances'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
